CREATE TABLE cakes (
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
price NUMERIC NOT NULL,
image VARCHAR(1000) NOT NULL,
description TEXT NOT NULL
);

CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
address VARCHAR(200) NOT NULL,
phone VARCHAR(200) NOT NULL
);

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
"clientId" INTEGER NOT NULL REFERENCES clients(id),
"cakeId" INTEGER NOT NULL REFERENCES cakes(id),
quantity INTEGER NOT NULL,
"createdAt" TIMESTAMP DEFAULT NOW(),
"totalPrice" NUMERIC NOT NULL
);